#! /bin/sh

# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# polybar
$HOME/.config/polybar/launch.sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# colors
bspc config normal_border_color "#555555"
bspc config active_border_color "#FF1300"
bspc config focused_border_color "#439ECF"
bspc config presel_feedback_color "#6272a4"


#### BSPWM configuration ####
bspc config border_radius                 8
bspc config border_width                  3
bspc config window_gap                    7
#bspc config top_padding                   0
#bspc config bottom_padding                0
#bspc config left_padding                  0
#bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Code desktop='^3'
bspc rule -a firefox desktop='^2'
bspc rule -a vlc desktop='^4'
bspc rule -a Xfce4-terminal desktop='^10'
bspc rule -a Codeblocks desktop='^9'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

