#!/bin/sh

# Prints the current volume or 🔇 if muted.

max=100

p() {
  vol="$(pamixer --get-volume)"
  if [ $vol -lt $max ]; then
    pamixer --allow-boost -i 5
  fi
}

# this for i3blocks
case $BLOCK_BUTTON in
 1) setsid -f "$TERMINAL" -e pulsemixer ;;
 2) pamixer -t ;;
 4) p ;;
 5) pamixer --allow-boost -d 5;;
 3) notify-send "📢 Volume module" "\- Shows volume 🔊, 🔇 if muted.
- Middle click to mute.
- Scroll to change." ;;
 6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

#[ $(pamixer --get-mute) = true ] && echo 🔇 && exit
[ $(pamixer --get-mute) = true ] && echo Mute && exit

vol="$(pamixer --get-volume)"

echo "$vol%"
